apiVersion: v1
kind: Service
metadata:
  name: observability-demo
  namespace: iom-madhu
spec:
  selector:
    app: observability-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    