apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: application-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: MNaaS-demo
    repoURL: 'https://github.com/Sarah123445/deployment-manifests.git'
    targetRevision: main
  syncPolicy:
    automated: {}
        