kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mnaas-demo-additonal
rules:
  - verbs:
      - '*'
    apiGroups:
      - ""
    resources:
      - configmaps
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mnaas-demo-additonal-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mnaas-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mnaas-demo-additonal