apiVersion: v1
kind: Service
metadata:
  name: user-service-jenkins
  namespace: mnaas-demo
spec:
  selector:
    app: user-service-jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    