kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-service-jenkins
  namespace: mnaas-demo
  labels:
    app: user-service-jenkins
    logFormat: json
    monitor: springboot
    prometheus: user-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-jenkins
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service-jenkins
        logFormat: json
        monitor: springboot
        prometheus: user-workloads
      annotations:
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: user-service-jenkins
          env:
            - name: MONGODB_USER
              valueFrom: 
                secretKeyRef:
                  key: MONGODB_USER
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  key: MONGODB_PASSWORD
                  name: mongodb-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: user-service-jenkins
          image: 'spencer94/user-service-jenkins:cc692896f645c059920c4b365b4776ba3776fb85ffa39731b08a1e7aa5ea3019'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30